### ISSUE TITLE
getting 404 error when user tries to cancel or go back to  checkout page

### ISSUE THREAD

**Issue by lijnam** [act360/fonepay-for-woocommerce#4] opened 2020-12-29 17:31 UTC
![image](https://user-images.githubusercontent.com/10097726/103302463-d86cf300-4a2b-11eb-9d7c-bb75e58db939.png)

**Comment by act360** [comment] 2020-12-31 04:11
Thank you for reporting this @lijnam . We'll liaise with Fonepay to get it resolved as soon as possible.

**Comment by act360** [comment] 2021-01-04 08:16
Hi @lijnam ,

We communicated this to Fonepay. Unfortunately they need to resolve this at their end for each merchant.
Please [get it touch](https://www.fonepay.com/contact-us) with them for further support if need be.

Closing this issue as it is not caused by the plugin.

Thank you,

**Closed by act360** 2021-01-04 08:16 UTC
